-- 1. Xóa database cũ nếu tồn tại để làm mới hoàn toàn
DROP DATABASE IF EXISTS qhtn_fashion;

-- 2. Tạo database mới
CREATE DATABASE qhtn_fashion CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE qhtn_fashion;

-- --------------------------------------------------------
-- 3. Bảng Users (Người dùng)
-- --------------------------------------------------------
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user',
    phone VARCHAR(15) DEFAULT NULL,
    avatar VARCHAR(255) DEFAULT 'default.jpg',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- --------------------------------------------------------
-- 4. Bảng Categories (Danh mục sản phẩm)
-- --------------------------------------------------------
CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- --------------------------------------------------------
-- 5. Bảng Products (Sản phẩm)
-- --------------------------------------------------------
CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL DEFAULT 0,
    image VARCHAR(255),
    description TEXT NULL,
    material VARCHAR(255) NULL,
    care VARCHAR(255) NULL,
    condition_note VARCHAR(255) NULL,
    deposit INT NULL,
    short_note VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Biến thể sản phẩm (size/màu/stock/giá riêng)
CREATE TABLE product_variants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    size VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    sku VARCHAR(100) NULL,
    price_override INT NULL,
    stock INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- --------------------------------------------------------
-- 6. Bảng Orders (Đơn hàng tổng)
-- --------------------------------------------------------
CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    total_price INT NOT NULL DEFAULT 0,
    status ENUM('pending', 'confirmed', 'ongoing', 'returned', 'cancelled') DEFAULT 'pending',
    payment_method VARCHAR(100) NULL,
    note TEXT,
    admin_notes TEXT,
    returned_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- --------------------------------------------------------
-- 7. Bảng Order Details (Chi tiết từng món trong đơn)
-- --------------------------------------------------------
CREATE TABLE order_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT,
    variant_id INT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price INT NOT NULL,
    rental_start DATETIME NULL,
    rental_end DATETIME NULL,
    duration_days INT NULL,
    status ENUM('pending', 'collected', 'in-transit', 'in-use', 'returned') DEFAULT 'pending',
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- --------------------------------------------------------
-- 8. Dữ liệu mẫu (Seed Data)
-- --------------------------------------------------------

-- Thêm Danh mục (ID sẽ tự nhảy từ 1 đến 6)
INSERT INTO categories (name, slug) VALUES 
('Áo Dài', 'ao-dai'),          -- ID 1
('Váy Thiết Kế', 'vay-thiet-ke'), -- ID 2
('Set Quần Áo', 'set-quan-ao'),   -- ID 3
('Phụ Kiện', 'phu-kien'),         -- ID 4
('Giày', 'giay'),                 -- ID 5
('Váy Đi Biển', 'vay-di-bien');   -- ID 6

-- Thêm Admin (mật khẩu: 123456)
INSERT INTO users (username, email, password, role)
VALUES 
('Minh Quyên', 'minhquyen@gmail.com', '$2y$10$/50Fxv23SzZi8bNclggcjui.krT8aOfqxQah6lEYw2fF1nyBcTgRO', 'admin'),
('Thảo Ngân', 'thaongan@gmail.com', '$2y$10$/50Fxv23SzZi8bNclggcjui.krT8aOfqxQah6lEYw2fF1nyBcTgRO', 'admin'),
('Diệu Huyền', 'dieuhuyen@gmail.com', '$2y$10$/50Fxv23SzZi8bNclggcjui.krT8aOfqxQah6lEYw2fF1nyBcTgRO', 'admin'),
('Phương Trinh', 'phuongtrinh@gmail.com', '$2y$10$/50Fxv23SzZi8bNclggcjui.krT8aOfqxQah6lEYw2fF1nyBcTgRO', 'admin');

-- Sản phẩm Áo Dài (Category ID = 1)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES 
('Áo Dài Việt Phục - Cổ Phục Việt Nam', 150000, 1, 'img/ad1.jpg', 'Áo dài phom chuẩn, tôn dáng, phù hợp chụp ảnh và sự kiện.', 'Lụa pha', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Phom chuẩn, hỗ trợ thử và chỉnh nhẹ'),
('Áo Dài Cách Tân', 150000, 1, 'img/ad2.jpg', 'Áo dài cách tân, dáng gọn, dễ phối phụ kiện.', 'Lụa pha', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thoáng mát, lên dáng đẹp'),
('Áo Dài Cách Tân', 150000, 1, 'img/ad3.jpg', 'Áo dài cách tân nhẹ nhàng, hợp chụp lookbook.', 'Voan lụa', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Chất mịn, đứng phom'),
('Áo Dài Cách Tân', 150000, 1, 'img/ad4.jpg', 'Thiết kế hiện đại, tôn chiều cao, phối quần lụa.', 'Lụa mềm', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Phù hợp sự kiện sáng'),
('Áo Dài Cách Tân Tay Lửng', 150000, 1, 'img/ad 5.jpg', 'Tay lửng thanh lịch, phù hợp dự lễ và chụp ảnh.', 'Lụa mờ', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nhẹ, dễ di chuyển'),
('Áo Dài Cách Tân Tay Phồng', 150000, 1, 'img/ad6.jpg', 'Tay phồng điểm nhấn, giúp vai thon.', 'Lụa pha organza', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nữ tính, trẻ trung'),
('Áo Dài Cách Tân Tay Phồng', 150000, 1, 'img/ad7.jpg', 'Thiết kế tay phồng sang, hợp tiệc cưới.', 'Lụa satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bồng nhẹ, đứng phom'),
('Áo Dài Lụa', 150000, 1, 'img/ad8.jpg', 'Áo dài lụa trơn, tối giản, dễ phối phụ kiện.', 'Lụa tơ', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tối giản, sang trọng'),
('Áo Dài Voan', 150000, 1, 'img/ad9.jpg', 'Voan nhẹ, thoáng, phù hợp chụp ngoại cảnh.', 'Voan lụa', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nhẹ, bay phom'),
('Áo Dài Hiện Đại', 150000, 1, 'img/ad10.jpg', 'Áo dài hiện đại, eo gọn, dáng ôm nhẹ.', 'Lụa lạnh', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Ôm nhẹ, tôn dáng'),
('Áo Dài Cách Tân Nữ', 150000, 1, 'img/ad11.jpg', 'Cách tân phối ren nhẹ, dịu dàng.', 'Lụa/ren', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nữ tính, mềm mại'),
('Áo Dài Yếm Cổ Tròn', 150000, 1, 'img/ad12.jpg', 'Yếm cổ tròn, trẻ trung, phù hợp dạ tiệc.', 'Lụa satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Mát, nổi bật'),
('Áo Dài Cách Tân Phối Váy', 150000, 1, 'img/ad13.jpg', 'Phối váy xòe nhẹ, mix đơn giản.', 'Lụa/voan', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Mix váy nhẹ nhàng'),
('Áo Dài Cách Tân Hiện Đại', 150000, 1, 'img/ad14.jpg', 'Form hiện đại, nẹp cổ tối giản.', 'Lụa mịn', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Đứng phom, dễ phối'),
('Áo Dài Cách Tân Tay phồng', 150000, 1, 'img/ad15.jpg', 'Tay phồng cao cấp, hợp studio.', 'Lụa pha organza', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tay phồng nổi bật'),
('Áo Dài Truyền Thống', 150000, 1, 'img/ad16.jpg', 'Truyền thống, họa tiết nhã, phù hợp lễ cưới.', 'Gấm nhẹ', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thanh lịch'),
('Áo Dài Truyền Thống', 150000, 1, 'img/ad17.jpg', 'Thiết kế truyền thống, cổ kín.', 'Gấm lụa', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Trang trọng'),
('Áo Dài Hiện Đại', 150000, 1, 'img/ad18.jpg', 'Áo dài phối tông hiện đại.', 'Lụa lạnh', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gọn gàng'),
('Áo Dài Hiện Đại', 150000, 1, 'img/ad19.jpg', 'Form ôm nhẹ, đường cắt tối giản.', 'Lụa trơn', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thoải mái'),
('Áo Dài Cách Tân Tay Lửng', 150000, 1, 'img/ad20.jpg', 'Tay lửng gọn gàng, di chuyển dễ.', 'Lụa pha', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gọn nhẹ');

-- Sản phẩm Váy Thiết Kế (Category ID = 2)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES 
('Váy Trễ Vai Thiết Kế', 100000, 2, 'img/vtk1.jpg', 'Đầm trễ vai tôn xương quai xanh, hợp tiệc và chụp ảnh.', 'Lụa satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Ôm nhẹ, tôn dáng'),
('Váy Trễ Vai Quyến Rũ', 100000, 2, 'img/vtk2.jpg', 'Đầm trễ vai ôm eo, tạo đường cong.', 'Lụa mềm', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Quyến rũ, nữ tính'),
('Đầm Dự Tiệc', 100000, 2, 'img/vtk3.jpg', 'Đầm tiệc sang trọng, phom chữ A.', 'Satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Lịch sự, sang'),
('Đầm Cổ Tròn Không Tay', 100000, 2, 'img/vtk4.jpg', 'Đầm không tay mát mẻ, phù hợp tiệc ngoài trời.', 'Lụa mát', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Mát, gọn'),
('Đầm Tay Tròn', 100000, 2, 'img/vtk5.jpg', 'Đầm tay tròn basic, dễ phối phụ kiện.', 'Lụa/voan', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Basic, dễ mặc'),
('Đầm Thiết Kế Dáng Tiểu Thư', 100000, 2, 'img/vtk6.jpg', 'Dáng tiểu thư bồng nhẹ, hợp dạo phố và tiệc.', 'Organza/lụa', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bồng nhẹ, nữ tính'),
('Đầm Cúp Ngực Ôm Dáng', 100000, 2, 'img/vtk7.jpg', 'Cúp ngực ôm, khoe vai, hợp sự kiện tối.', 'Satin co giãn', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Ôm sát, gợi cảm'),
('Đầm Yếm Dáng Ngắn', 100000, 2, 'img/vtk8.jpg', 'Đầm yếm ngắn trẻ trung, dễ di chuyển.', 'Lụa lạnh', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Trẻ trung'),
('Đầm Xẻ Cổ V + Áo Choàng', 100000, 2, 'img/vtk9.jpg', 'Xẻ cổ V đi kèm áo choàng, nổi bật sân khấu.', 'Satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nổi bật sự kiện'),
('Đầm Cổ Yếm Xòe', 100000, 2, 'img/vtk10.jpg', 'Cổ yếm xòe nhẹ, che khuyết điểm.', 'Lụa mềm', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Xòe nhẹ, thoải mái'),
('Đầm Yếm Tầng', 100000, 2, 'img/vtk11.jpg', 'Yếm tầng bồng, hợp chụp lookbook.', 'Voan tầng', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bồng bềnh'),
('Đầm Tiểu Thư Cổ Yếm', 100000, 2, 'img/vtk12.jpg', 'Tiểu thư cổ yếm, cắt xẻ vừa phải.', 'Lụa/voan', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nữ tính'),
('Đầm Cúp Ngực Cao Cấp', 100000, 2, 'img/vtk13.jpg', 'Cúp ngực cao cấp, phom ôm, hợp tiệc tối.', 'Satin dày', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Sang trọng'),
('Đầm Cổ Vuông Nơ', 100000, 2, 'img/vtk14.jpg', 'Cổ vuông nơ, tôn vai và cổ.', 'Lụa mịn', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Dễ thương'),
('Đầm Trễ Vai Quyến Rũ', 100000, 2, 'img/vtk15.jpg', 'Trễ vai quyến rũ, phom ôm.', 'Satin', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gợi cảm'),
('Đầm Cổ Yếm Bồng', 100000, 2, 'img/vtk16.jpg', 'Cổ yếm bồng nhẹ, hợp tiệc ngày.', 'Organza/lụa', 'Hấp/ủi hơi nước, không giặt máy', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bồng nhẹ');

-- Set Quần Áo (Category ID = 3)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES
('Sét Quần Áo Tay Bồng', 100000, 3, 'img/aq1.jpg', 'Set tay bồng trẻ trung, phối quần ống rộng.', 'Cotton/voan', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thoáng, dễ mặc'),
('Sét Quần Áo Không Tay', 100000, 3, 'img/aq2.jpg', 'Không tay mát mẻ, hợp dạo phố.', 'Cotton lạnh', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gọn, mát'),
('Sét Quần Áo Yếm', 100000, 3, 'img/aq3.jpg', 'Yếm hiện đại, phối quần suông.', 'Lụa pha', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Trẻ trung'),
('Sét Váy Yếm Nơ', 100000, 3, 'img/aq4.jpg', 'Yếm nơ nữ tính, dáng váy nhẹ.', 'Lụa/voan', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nữ tính'),
('Sét Áo Yếm Ren + Quần Jean Ống Rộng', 100000, 3, 'img/aq5.jpg', 'Áo ren yếm phối jean ống rộng cá tính.', 'Ren/jean', 'Giặt tay áo; jean giặt nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Cá tính'),
('Sét Áo Cổ Nơ + Quần Jean Ống Đứng', 100000, 3, 'img/aq6.jpg', 'Áo cổ nơ thanh lịch phối jean ống đứng.', 'Voan/jean', 'Giặt tay áo; jean giặt nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thanh lịch'),
('Sét Áo Chiết Eo Không Tay + Quần Ống Loe', 100000, 3, 'img/aq7.jpg', 'Áo chiết eo + quần ống loe tôn chân.', 'Lụa/cotton', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tôn dáng'),
('Sét Áo Có Cổ Không Tay + Quần Jean Ống Xuông', 100000, 3, 'img/aq8.jpg', 'Áo cổ gọn phối jean xuông, dễ mix.', 'Cotton/jean', 'Giặt tay áo; jean giặt nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Dễ phối'),
('Sét Áo Đen Eo + Chân Váy Dài Xếp Ly', 100000, 3, 'img/aq9.jpg', 'Áo ôm eo + váy xếp ly thanh lịch.', 'Lụa/voan', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Thanh lịch'),
('Sét Áo Croptop Cổ V + Quần Tây Ống Rộng Cạp Cao', 100000, 3, 'img/aq10.jpg', 'Croptop cổ V phối quần tây cạp cao.', 'Cotton/ploy', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Cao ráo'),
('Sét Áo Sơ Mi + Quần Ống Xuông', 100000, 3, 'img/aq11.jpg', 'Sơ mi nhẹ phối quần xuông, công sở.', 'Cotton/ploy', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gọn gàng'),
('Sét Đồ Blazer + Áo Croptop + Quần Ống Loe', 100000, 3, 'img/aq12.jpg', 'Blazer croptop + quần loe, cá tính.', 'Poly/jean', 'Hấp nhẹ blazer, giặt tay áo', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Cá tính'),
('Sét Sơ Mi + Quần Jean + Khăn Lụa', 100000, 3, 'img/aq13.jpg', 'Sơ mi + jean + khăn lụa, trẻ trung.', 'Cotton/jean/lụa', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tươi trẻ'),
('Sét Áo Lụa Xách Nách + Chân Váy Ngắn Dáng Ôm', 100000, 3, 'img/aq14.jpg', 'Áo lụa sát nách + váy ôm mini.', 'Lụa/ploy', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Sexy nhẹ'),
('Sét Áo Vest + Quần Sort', 100000, 3, 'img/aq15.jpg', 'Áo vest ngắn + short, năng động.', 'Poly/ploy', 'Hấp nhẹ vest, giặt tay quần', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Năng động'),
('Sét Áo Hai Dây + Váy Ôm', 100000, 3, 'img/aq16.jpg', 'Hai dây + váy ôm, hợp tiệc tối.', 'Lụa co giãn', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Gọn, ôm'),
('Sét Áo Corset Lệch Vai Bánh Bèo', 100000, 3, 'img/aq17.jpg', 'Corset lệch vai bánh bèo, tôn eo.', 'Lụa/organza', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tôn eo'),
('Sét Áo Lệch Vai Bèo Tầng + Quần Sort Cạp Cao', 100000, 3, 'img/aq18.jpg', 'Lệch vai bèo tầng + short cạp cao.', 'Voan/ploy', 'Giặt tay, ủi nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Đi biển, dạo phố'),
('Sét Áo Khoác Tweed Hoa + Chân Váy Xếp Ly Ngắn', 100000, 3, 'img/aq19.jpg', 'Khoác tweed hoa + váy xếp ly ngắn.', 'Tweed/voan', 'Hấp/ủi hơi nước', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tweed sang');

-- Phụ Kiện (Category ID = 4)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES
('Bông Tai Dài Xoắn Đính Ngọc Trai', 20000, 4, 'img/pk1.jpg', 'Khuyên tai dài đính ngọc trai, điểm nhấn tinh tế.', 'Hợp kim mạ', 'Lau khô, tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Nhẹ, không nặng tai'),
('Bông Tai Đá Pha Lê Dáng Giọt Nước', 20000, 4, 'img/pk2.jpg', 'Pha lê giọt nước lấp lánh.', 'Hợp kim/pha lê', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Sáng sân khấu'),
('Bông Tai Hoa Đính Đá Kết Hợp Ngọc Trai', 20000, 4, 'img/pk3.jpg', 'Hoa đá + ngọc trai, nữ tính.', 'Hợp kim/đá/pearl', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Nữ tính'),
('Bộ Trang Sức Ngọc Trai Cơ Bản', 20000, 4, 'img/pk4.jpg', 'Bộ ngọc trai tối giản.', 'Pearl nhân tạo', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thanh lịch'),
('Bộ Trang Sức Ngọc Trai Tối Giản', 20000, 4, 'img/pk5.jpg', 'Pearl tối giản, dễ phối.', 'Pearl nhân tạo', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Basic'),
('Bộ Trang Sức Đá Giọt Nước', 20000, 4, 'img/pk6.jpg', 'Đá giọt nước, sáng sân khấu.', 'Pha lê', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Lấp lánh'),
('Vòng Cổ Đá Dáng Cổ Điển', 20000, 4, 'img/pk7.jpg', 'Vòng đá phong cách cổ điển.', 'Hợp kim/đá', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Vintage nhẹ'),
('Nơ Ruy Băng', 20000, 4, 'img/pk8.jpg', 'Nơ ruy băng mềm, dễ cột tóc.', 'Vải', 'Giặt tay nhẹ', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Nhẹ'),
('Nơ Cài Tóc Nhung Đính Đá', 20000, 4, 'img/pk9.jpg', 'Nơ nhung đính đá, nổi bật.', 'Nhung/đá', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Nổi bật'),
('Băng Đô Nơ', 20000, 4, 'img/pk10.jpg', 'Băng đô nơ mềm mại.', 'Vải', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Êm, nhẹ'),
('Băng Đô Cài Tóc Nhung Đính Đá', 20000, 4, 'img/pk11.jpg', 'Băng đô nhung đính đá.', 'Nhung/đá', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Sang nhẹ'),
('Mũ BAKER BOY', 20000, 4, 'img/pk12.jpg', 'Mũ baker boy cá tính.', 'Kaki', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Cá tính'),
('Mũ Vành Rộng', 20000, 4, 'img/pk13.jpg', 'Mũ vành rộng che nắng.', 'Cói/vải', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Đi biển'),
('Mũ Nồi Có Dây Ruy Băng', 20000, 4, 'img/pk14.jpg', 'Mũ nồi có dây, style Pháp.', 'Nỉ', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Classic'),
('Mũ Boater Vành Rộng', 20000, 4, 'img/pk15.jpg', 'Boater vành rộng vintage.', 'Cói/vải', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Vintage'),
('Đồng Hồ Nữ', 20000, 4, 'img/pk16.jpg', 'Đồng hồ nữ basic.', 'Thép/da', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Tinh gọn'),
('Đồng Hồ RICHARD MILLE Dòng Nữ', 20000, 4, 'img/pk17.jpg', 'RM nữ bản thời trang.', 'Thép/da', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Cá tính'),
('Đồng Hồ Nữ HERMES Dây Da', 20000, 4, 'img/pk18.jpg', 'Hermes dây da nữ tính.', 'Thép/da', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Sang nhẹ'),
('Đồng Hồ Dây Da CHOPARD', 20000, 4, 'img/pk19.jpg', 'Chopard dây da, thanh lịch.', 'Thép/da', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thanh lịch'),
('Đồng Hồ Dây Da VERSACE Màu Xanh', 20000, 4, 'img/pk20.jpg', 'Versace xanh nổi bật.', 'Thép/da', 'Tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Điểm nhấn'),
('Kính Gọng Ovan Kim Loại Đính Đá', 20000, 4, 'img/pk21.jpg', 'Kính gọng oval đính đá.', 'Kim loại/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Lấp lánh'),
('Kính Mắt Dáng Ovan Nhỏ Gọng Kim Loại', 20000, 4, 'img/pk22.jpg', 'Kính oval nhỏ, gọng kim loại.', 'Kim loại/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Nhỏ gọn'),
('Kính Mắt MIU MIU Dáng Chữ Nhật', 20000, 4, 'img/pk23.jpg', 'Kính chữ nhật MIU MIU thời trang.', 'Nhựa/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thời trang'),
('Kính Mắt MIU MIU Dáng Ovan Gọng Kim Loại', 20000, 4, 'img/pk24.jpg', 'Kính oval MIU MIU gọng kim loại.', 'Kim loại/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thanh mảnh'),
('Kính Mắt BVLGARI Dòng Serfenti', 20000, 4, 'img/pk25.jpg', 'Kính BVLGARI Serpenti nổi bật.', 'Kim loại/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Cao cấp'),
('Kính Mắt MIU MIU Dáng Tròn', 20000, 4, 'img/pk26.jpg', 'Kính tròn MIU MIU dễ thương.', 'Nhựa/kính', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Dễ thương'),
('Túi CHANEL CoCo Handle', 30000, 4, 'img/tui1.jpg', 'Túi CoCo Handle sang trọng.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Sang trọng'),
('Túi DIOR Caro', 30000, 4, 'img/tui2.jpg', 'Túi Dior Caro, dây xích.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Iconic'),
('Túi DIOR Kèm Charm', 30000, 4, 'img/tui3.jpg', 'Túi Dior charm điểm nhấn.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Charm nổi bật'),
('Túi DIOR Màu Kem', 30000, 4, 'img/tui4.jpg', 'Dior màu kem dễ phối.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Dễ phối'),
('Túi DIOR Đỏ/Đen', 30000, 4, 'img/tui5.jpg', 'Dior đỏ/đen cá tính.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Cá tính'),
('Túi JACQUEMUS', 30000, 4, 'img/tui6.jpg', 'Jacquemus mini thời trang.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Mini trend'),
('3 Kiểu Túi CELINE Triomphe', 30000, 4, 'img/tui7.jpg', 'Celine Triomphe thanh lịch.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Classic'),
('Túi DIOR', 30000, 4, 'img/tui8.jpg', 'Túi Dior basic.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Basic'),
('Túi DIOR', 30000, 4, 'img/tui9.jpg', 'Túi Dior phối màu.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Mix màu'),
('Túi CHANEL', 30000, 4, 'img/tui10.jpg', 'Túi Chanel thanh lịch.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thanh lịch'),
('Túi FENDI', 30000, 4, 'img/tui11.jpg', 'Fendi cá tính.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Cá tính'),
('Túi LOUIS VUITTON', 30000, 4, 'img/tui12.jpg', 'LV thời trang.', 'Da tổng hợp', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Thời trang'),
('Túi CHANEL Bản Nhung', 30000, 4, 'img/tui13.jpg', 'Chanel nhung sang.', 'Nhung', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 100000, 'Mềm sang');

-- Giày (Category ID = 5)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES
('Giày Búp Bê JIMMY CHOO Có Quai Đính Đá', 50000, 5, 'img/giay1.jpg', 'Giày búp bê đính đá, êm chân.', 'Da/satin', 'Lau khô, tránh nước', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Êm, chắc chân'),
('Giày Cao Gót JIMMY CHOO', 50000, 5, 'img/giay2.jpg', 'Cao gót JIMMY CHOO thanh lịch.', 'Satin/da', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Êm gót'),
('Giày Co Gót SLINGBACK Dạng Mũi Nhọn', 50000, 5, 'img/giay3.jpg', 'Slingback mũi nhọn tôn chân.', 'Da/satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Ôm chân'),
('Giày DIOR SLINGBACK Mũi Nhọn - Đế Thấp', 50000, 5, 'img/giay4.jpg', 'Dior slingback đế thấp dễ đi.', 'Da/satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Dễ đi'),
('Giày DIOR SLINGBACK Phiên Bản Vải Ren', 50000, 5, 'img/giay5.jpg', 'Slingback ren nhẹ nhàng.', 'Ren/da', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Nhẹ'),
('Giày JIMMY CHOO SLINGBACK Mũi Nhọn Đính Nơ Lớn', 50000, 5, 'img/giay6.jpg', 'Slingback nơ lớn, nổi bật.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Nổi bật'),
('Giày Cao Gót Mũi Nhọn Đính Nơ Ngọc Trai', 50000, 5, 'img/giay7.jpg', 'Cao gót nơ ngọc trai.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Thanh lịch'),
('Giày Cao Gót Mũi Nhọn ĐÍnh Nơ Ngọc Trai', 50000, 5, 'img/giay8.jpg', 'Mũi nhọn nơ ngọc trai bản khác.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Bản khác'),
('Giày Cao Gót ROGER VIVIER', 50000, 5, 'img/giay9.jpg', 'Roger Vivier sang trọng.', 'Da/satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Sang'),
('Giày Cao Gót LUIS VUITTON SLINGBACK Mũi Nhọn Đính Pha Lê', 50000, 5, 'img/giay10.jpg', 'LV slingback pha lê.', 'Satin/pha lê', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Lấp lánh'),
('Giày Cao Gót MIU MIU Mũi Nhọn Đính Nơ', 50000, 5, 'img/giay11.jpg', 'MIU MIU nơ, trẻ trung.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Trẻ trung'),
('Giày Cao Gót Mũi NHọn MIU MIU Mule Hở Gót Đính Hoa', 50000, 5, 'img/giay12.jpg', 'Mule hở gót đính hoa.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Dễ xỏ'),
('Giày Cao Gót Mule Màu Hồng Phấn Chất Liệu Satin', 50000, 5, 'img/giay13.jpg', 'Mule satin hồng phấn.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Ngọt ngào'),
('Giày Cao Gót Đính Hoa Hồng Vải Lớn', 50000, 5, 'img/giay14.jpg', 'Hoa hồng vải lớn, statement.', 'Satin/vải', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Statement'),
('Giày Cao Gót ZARA Mũi Nhọn', 50000, 5, 'img/giay15.jpg', 'Cao gót Zara cơ bản.', 'PU/satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Basic'),
('Giày Cao Gót Mũi Nhọn Họa Tiết Caro Có ĐÍnh Nơ', 50000, 5, 'img/giay16.jpg', 'Họa tiết caro nơ.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Caro nổi bật'),
('Giày Cao Gót GUCCI Mũi Nhọn Đính Cherry', 50000, 5, 'img/giay17.jpg', 'Gucci cherry độc đáo.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Độc đáo'),
('Giày Cao Gót Quai Mảnh Màu Đỏ Đính Hoa Vảy Nổi', 50000, 5, 'img/giay18.jpg', 'Quai mảnh đỏ đính hoa.', 'Satin', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Đỏ nổi bật'),
('Boot Da Cổ Lủng Phong Cách Piker', 50000, 5, 'img/giay19.jpg', 'Boot da cổ lửng phong cách biker.', 'Da PU', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Cá tính'),
('Boot Da Lộn Cổ Nhún Gót Cao', 50000, 5, 'img/giay20.jpg', 'Boot da lộn cổ nhún.', 'Da lộn', 'Chải khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Ấm, êm'),
('Boot Cao Cổ Dáng Thẳng', 50000, 5, 'img/giay21.jpg', 'Boot cao cổ dáng thẳng.', 'Da PU', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Thẳng gọn'),
('Boot Cao Cổ Dáng Trụ', 50000, 5, 'img/giay22.jpg', 'Boot cao cổ dáng trụ.', 'Da PU', 'Lau khô', 'Đã vệ sinh, sẵn sàng thuê', 200000, 'Vững chân');

-- Váy Đi Biển (Category ID = 6)
INSERT INTO products (name, price, category_id, image, description, material, care, condition_note, deposit, short_note) VALUES
('Váy Maxi Hoa Nhí', 100000, 6, 'img/vmaxi1.jpg', 'Váy maxi hoa nhí, nhẹ, hợp đi biển.', 'Voan nhẹ', 'Giặt tay, phơi mát', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bay nhẹ'),
('Váy Maxi Cổ Yếm', 100000, 6, 'img/vmaxi2.jpg', 'Maxi cổ yếm khoe vai.', 'Voan/lụa', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Hở vai dịu'),
('Váy Maxi Kẻ Dọc Cổ Yếm', 100000, 6, 'img/vmaxi3.jpg', 'Maxi kẻ dọc cổ yếm, tôn chiều cao.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tôn dáng'),
('Váy Maxi Cổ Yếm Xếp Ly', 100000, 6, 'img/vmaxi4.jpg', 'Cổ yếm xếp ly, nhẹ nhàng.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Xếp ly mềm'),
('Set Hai Mảnh Hoa Nhí Dáng Maxi', 100000, 6, 'img/vmaxi5.jpg', 'Set hai mảnh maxi hoa nhí.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Đi biển'),
('Set Maxi Tầng Dáng Corset', 100000, 6, 'img/vmaxi6.jpg', 'Maxi tầng corset, ôm eo.', 'Voan/lụa', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Ôm eo'),
('Váy Maxi Lụa Trắng Tối Giản', 100000, 6, 'img/vmaxi7.jpg', 'Maxi lụa trắng tối giản.', 'Lụa', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Tối giản'),
('Set Áo Váy Hoa Hồng', 100000, 6, 'img/vmaxi8.jpg', 'Set áo váy hoa hồng, nổi bật.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Hoa nổi'),
('Váy Maxi Bồng Lưng Hở', 100000, 6, 'img/vmaxi9.jpg', 'Maxi bồng lưng hở sexy.', 'Voan/lụa', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Sexy nhẹ'),
('Váy Maxi Cổ V Xẻ Tà', 100000, 6, 'img/vmaxi10.jpg', 'Maxi cổ V xẻ tà.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Xẻ tà nhẹ'),
('Set Áo Váy Maxi Hai Dây', 100000, 6, 'img/vmaxi11.jpg', 'Maxi hai dây set áo váy.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Mát'),
('Váy Maxi Tay Bồng', 100000, 6, 'img/vmaxi12.jpg', 'Maxi tay bồng lãng mạn.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Bồng bềnh'),
('Váy Maxi Cổ V Ôm', 100000, 6, 'img/vmaxi13.jpg', 'Maxi cổ V ôm eo.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Ôm eo'),
('Váy Maxi 4 Tầng', 100000, 6, 'img/vmaxi14.jpg', 'Maxi 4 tầng bay nhẹ.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Nhiều tầng'),
('Váy Maxi Tầng Hai Dây', 100000, 6, 'img/vmaxi15.jpg', 'Maxi tầng hai dây.', 'Voan', 'Giặt tay', 'Đã vệ sinh, sẵn sàng thuê', 300000, 'Hai dây');

-- Biến thể sản phẩm (size/màu/stock)
INSERT INTO product_variants (product_id, size, color, sku, price_override, stock) VALUES
-- Áo Dài 1-20
(1, 'S', 'Trắng', 'AD01-S-TRANG', NULL, 2),
(1, 'M', 'Hồng', 'AD01-M-HONG', NULL, 3),
(1, 'L', 'Đen', 'AD01-L-DEN', NULL, 2),
(2, 'S', 'Trắng', 'AD02-S-TRANG', NULL, 2),
(2, 'M', 'Hồng', 'AD02-M-HONG', NULL, 3),
(2, 'L', 'Đen', 'AD02-L-DEN', NULL, 2),
(3, 'S', 'Trắng', 'AD03-S-TRANG', NULL, 2),
(3, 'M', 'Be', 'AD03-M-BE', NULL, 3),
(3, 'L', 'Đen', 'AD03-L-DEN', NULL, 2),
(4, 'S', 'Trắng', 'AD04-S-TRANG', NULL, 2),
(4, 'M', 'Hồng', 'AD04-M-HONG', NULL, 3),
(4, 'L', 'Đen', 'AD04-L-DEN', NULL, 2),
(5, 'S', 'Trắng', 'AD05-S-TRANG', NULL, 2),
(5, 'M', 'Hồng', 'AD05-M-HONG', NULL, 3),
(5, 'L', 'Đen', 'AD05-L-DEN', NULL, 2),
(6, 'S', 'Trắng', 'AD06-S-TRANG', NULL, 2),
(6, 'M', 'Hồng', 'AD06-M-HONG', NULL, 3),
(6, 'L', 'Đen', 'AD06-L-DEN', NULL, 2),
(7, 'S', 'Trắng', 'AD07-S-TRANG', NULL, 2),
(7, 'M', 'Be', 'AD07-M-BE', NULL, 3),
(7, 'L', 'Đen', 'AD07-L-DEN', NULL, 2),
(8, 'S', 'Trắng', 'AD08-S-TRANG', NULL, 2),
(8, 'M', 'Hồng', 'AD08-M-HONG', NULL, 3),
(8, 'L', 'Đen', 'AD08-L-DEN', NULL, 2),
(9, 'S', 'Trắng', 'AD09-S-TRANG', NULL, 2),
(9, 'M', 'Be', 'AD09-M-BE', NULL, 3),
(9, 'L', 'Đen', 'AD09-L-DEN', NULL, 2),
(10, 'S', 'Trắng', 'AD10-S-TRANG', NULL, 2),
(10, 'M', 'Hồng', 'AD10-M-HONG', NULL, 3),
(10, 'L', 'Đen', 'AD10-L-DEN', NULL, 2),
(11, 'S', 'Trắng', 'AD11-S-TRANG', NULL, 2),
(11, 'M', 'Be', 'AD11-M-BE', NULL, 3),
(11, 'L', 'Đen', 'AD11-L-DEN', NULL, 2),
(12, 'S', 'Trắng', 'AD12-S-TRANG', NULL, 2),
(12, 'M', 'Hồng', 'AD12-M-HONG', NULL, 3),
(12, 'L', 'Đen', 'AD12-L-DEN', NULL, 2),
(13, 'S', 'Trắng', 'AD13-S-TRANG', NULL, 2),
(13, 'M', 'Be', 'AD13-M-BE', NULL, 3),
(13, 'L', 'Đen', 'AD13-L-DEN', NULL, 2),
(14, 'S', 'Trắng', 'AD14-S-TRANG', NULL, 2),
(14, 'M', 'Hồng', 'AD14-M-HONG', NULL, 3),
(14, 'L', 'Đen', 'AD14-L-DEN', NULL, 2),
(15, 'S', 'Trắng', 'AD15-S-TRANG', NULL, 2),
(15, 'M', 'Be', 'AD15-M-BE', NULL, 3),
(15, 'L', 'Đen', 'AD15-L-DEN', NULL, 2),
(16, 'S', 'Trắng', 'AD16-S-TRANG', NULL, 2),
(16, 'M', 'Hồng', 'AD16-M-HONG', NULL, 3),
(16, 'L', 'Đen', 'AD16-L-DEN', NULL, 2),
(17, 'S', 'Trắng', 'AD17-S-TRANG', NULL, 2),
(17, 'M', 'Be', 'AD17-M-BE', NULL, 3),
(17, 'L', 'Đen', 'AD17-L-DEN', NULL, 2),
(18, 'S', 'Trắng', 'AD18-S-TRANG', NULL, 2),
(18, 'M', 'Hồng', 'AD18-M-HONG', NULL, 3),
(18, 'L', 'Đen', 'AD18-L-DEN', NULL, 2),
(19, 'S', 'Trắng', 'AD19-S-TRANG', NULL, 2),
(19, 'M', 'Be', 'AD19-M-BE', NULL, 3),
(19, 'L', 'Đen', 'AD19-L-DEN', NULL, 2),
(20, 'S', 'Trắng', 'AD20-S-TRANG', NULL, 2),
(20, 'M', 'Hồng', 'AD20-M-HONG', NULL, 3),
(20, 'L', 'Đen', 'AD20-L-DEN', NULL, 2),
-- Váy Thiết Kế 21-36
(21, 'S', 'Đỏ', 'VTK21-S-DO', NULL, 2),
(21, 'M', 'Hồng', 'VTK21-M-HONG', NULL, 3),
(21, 'L', 'Đen', 'VTK21-L-DEN', NULL, 2),
(22, 'S', 'Đen', 'VTK22-S-DEN', NULL, 2),
(22, 'M', 'Hồng', 'VTK22-M-HONG', NULL, 3),
(22, 'L', 'Be', 'VTK22-L-BE', NULL, 2),
(23, 'S', 'Đỏ', 'VTK23-S-DO', NULL, 2),
(23, 'M', 'Be', 'VTK23-M-BE', NULL, 3),
(23, 'L', 'Đen', 'VTK23-L-DEN', NULL, 2),
(24, 'S', 'Trắng', 'VTK24-S-TRANG', NULL, 2),
(24, 'M', 'Be', 'VTK24-M-BE', NULL, 3),
(24, 'L', 'Đen', 'VTK24-L-DEN', NULL, 2),
(25, 'S', 'Trắng', 'VTK25-S-TRANG', NULL, 2),
(25, 'M', 'Hồng', 'VTK25-M-HONG', NULL, 3),
(25, 'L', 'Đen', 'VTK25-L-DEN', NULL, 2),
(26, 'S', 'Hồng', 'VTK26-S-HONG', NULL, 2),
(26, 'M', 'Be', 'VTK26-M-BE', NULL, 3),
(26, 'L', 'Đen', 'VTK26-L-DEN', NULL, 2),
(27, 'S', 'Đen', 'VTK27-S-DEN', NULL, 2),
(27, 'M', 'Be', 'VTK27-M-BE', NULL, 3),
(27, 'L', 'Đỏ', 'VTK27-L-DO', NULL, 2),
(28, 'S', 'Trắng', 'VTK28-S-TRANG', NULL, 2),
(28, 'M', 'Hồng', 'VTK28-M-HONG', NULL, 3),
(28, 'L', 'Đen', 'VTK28-L-DEN', NULL, 2),
(29, 'S', 'Đỏ', 'VTK29-S-DO', NULL, 2),
(29, 'M', 'Be', 'VTK29-M-BE', NULL, 3),
(29, 'L', 'Đen', 'VTK29-L-DEN', NULL, 2),
(30, 'S', 'Trắng', 'VTK30-S-TRANG', NULL, 2),
(30, 'M', 'Hồng', 'VTK30-M-HONG', NULL, 3),
(30, 'L', 'Đen', 'VTK30-L-DEN', NULL, 2),
(31, 'S', 'Trắng', 'VTK31-S-TRANG', NULL, 2),
(31, 'M', 'Hồng', 'VTK31-M-HONG', NULL, 3),
(31, 'L', 'Đen', 'VTK31-L-DEN', NULL, 2),
(32, 'S', 'Be', 'VTK32-S-BE', NULL, 2),
(32, 'M', 'Hồng', 'VTK32-M-HONG', NULL, 3),
(32, 'L', 'Đen', 'VTK32-L-DEN', NULL, 2),
(33, 'S', 'Đen', 'VTK33-S-DEN', NULL, 2),
(33, 'M', 'Be', 'VTK33-M-BE', NULL, 3),
(33, 'L', 'Đỏ', 'VTK33-L-DO', NULL, 2),
(34, 'S', 'Trắng', 'VTK34-S-TRANG', NULL, 2),
(34, 'M', 'Hồng', 'VTK34-M-HONG', NULL, 3),
(34, 'L', 'Đen', 'VTK34-L-DEN', NULL, 2),
(35, 'S', 'Đỏ', 'VTK35-S-DO', NULL, 2),
(35, 'M', 'Be', 'VTK35-M-BE', NULL, 3),
(35, 'L', 'Đen', 'VTK35-L-DEN', NULL, 2),
(36, 'S', 'Trắng', 'VTK36-S-TRANG', NULL, 2),
(36, 'M', 'Hồng', 'VTK36-M-HONG', NULL, 3),
(36, 'L', 'Đen', 'VTK36-L-DEN', NULL, 2),
-- Set Quần Áo 37-55
(37, 'S', 'Be', 'AQS37-S-BE', NULL, 2),
(37, 'M', 'Hồng', 'AQS37-M-HONG', NULL, 3),
(37, 'L', 'Đen', 'AQS37-L-DEN', NULL, 2),
(38, 'S', 'Trắng', 'AQS38-S-TRANG', NULL, 2),
(38, 'M', 'Be', 'AQS38-M-BE', NULL, 3),
(38, 'L', 'Đen', 'AQS38-L-DEN', NULL, 2),
(39, 'S', 'Trắng', 'AQS39-S-TRANG', NULL, 2),
(39, 'M', 'Be', 'AQS39-M-BE', NULL, 3),
(39, 'L', 'Đen', 'AQS39-L-DEN', NULL, 2),
(40, 'S', 'Trắng', 'AQS40-S-TRANG', NULL, 2),
(40, 'M', 'Hồng', 'AQS40-M-HONG', NULL, 3),
(40, 'L', 'Đen', 'AQS40-L-DEN', NULL, 2),
(41, 'S', 'Trắng', 'AQS41-S-TRANG', NULL, 2),
(41, 'M', 'Be', 'AQS41-M-BE', NULL, 3),
(41, 'L', 'Đen', 'AQS41-L-DEN', NULL, 2),
(42, 'S', 'Trắng', 'AQS42-S-TRANG', NULL, 2),
(42, 'M', 'Hồng', 'AQS42-M-HONG', NULL, 3),
(42, 'L', 'Đen', 'AQS42-L-DEN', NULL, 2),
(43, 'S', 'Trắng', 'AQS43-S-TRANG', NULL, 2),
(43, 'M', 'Be', 'AQS43-M-BE', NULL, 3),
(43, 'L', 'Đen', 'AQS43-L-DEN', NULL, 2),
(44, 'S', 'Trắng', 'AQS44-S-TRANG', NULL, 2),
(44, 'M', 'Hồng', 'AQS44-M-HONG', NULL, 3),
(44, 'L', 'Đen', 'AQS44-L-DEN', NULL, 2),
(45, 'S', 'Trắng', 'AQS45-S-TRANG', NULL, 2),
(45, 'M', 'Be', 'AQS45-M-BE', NULL, 3),
(45, 'L', 'Đen', 'AQS45-L-DEN', NULL, 2),
(46, 'S', 'Trắng', 'AQS46-S-TRANG', NULL, 2),
(46, 'M', 'Hồng', 'AQS46-M-HONG', NULL, 3),
(46, 'L', 'Đen', 'AQS46-L-DEN', NULL, 2),
(47, 'S', 'Trắng', 'AQS47-S-TRANG', NULL, 2),
(47, 'M', 'Be', 'AQS47-M-BE', NULL, 3),
(47, 'L', 'Đen', 'AQS47-L-DEN', NULL, 2),
(48, 'S', 'Trắng', 'AQS48-S-TRANG', NULL, 2),
(48, 'M', 'Hồng', 'AQS48-M-HONG', NULL, 3),
(48, 'L', 'Đen', 'AQS48-L-DEN', NULL, 2),
(49, 'S', 'Trắng', 'AQS49-S-TRANG', NULL, 2),
(49, 'M', 'Be', 'AQS49-M-BE', NULL, 3),
(49, 'L', 'Đen', 'AQS49-L-DEN', NULL, 2),
(50, 'S', 'Trắng', 'AQS50-S-TRANG', NULL, 2),
(50, 'M', 'Hồng', 'AQS50-M-HONG', NULL, 3),
(50, 'L', 'Đen', 'AQS50-L-DEN', NULL, 2),
(51, 'S', 'Trắng', 'AQS51-S-TRANG', NULL, 2),
(51, 'M', 'Be', 'AQS51-M-BE', NULL, 3),
(51, 'L', 'Đen', 'AQS51-L-DEN', NULL, 2),
(52, 'S', 'Trắng', 'AQS52-S-TRANG', NULL, 2),
(52, 'M', 'Hồng', 'AQS52-M-HONG', NULL, 3),
(52, 'L', 'Đen', 'AQS52-L-DEN', NULL, 2),
(53, 'S', 'Trắng', 'AQS53-S-TRANG', NULL, 2),
(53, 'M', 'Be', 'AQS53-M-BE', NULL, 3),
(53, 'L', 'Đen', 'AQS53-L-DEN', NULL, 2),
(54, 'S', 'Trắng', 'AQS54-S-TRANG', NULL, 2),
(54, 'M', 'Hồng', 'AQS54-M-HONG', NULL, 3),
(54, 'L', 'Đen', 'AQS54-L-DEN', NULL, 2),
(55, 'S', 'Trắng', 'AQS55-S-TRANG', NULL, 2),
(55, 'M', 'Be', 'AQS55-M-BE', NULL, 3),
(55, 'L', 'Đen', 'AQS55-L-DEN', NULL, 2),
-- Phụ kiện 56-94 (one size)
(56, 'OS', 'Bạc', 'PK56-OS', NULL, 8),
(57, 'OS', 'Bạc', 'PK57-OS', NULL, 8),
(58, 'OS', 'Bạc', 'PK58-OS', NULL, 8),
(59, 'OS', 'Trắng', 'PK59-OS', NULL, 8),
(60, 'OS', 'Trắng', 'PK60-OS', NULL, 8),
(61, 'OS', 'Bạc', 'PK61-OS', NULL, 8),
(62, 'OS', 'Bạc', 'PK62-OS', NULL, 8),
(63, 'OS', 'Hồng', 'PK63-OS', NULL, 10),
(64, 'OS', 'Đen', 'PK64-OS', NULL, 10),
(65, 'OS', 'Đỏ', 'PK65-OS', NULL, 10),
(66, 'OS', 'Hồng', 'PK66-OS', NULL, 10),
(67, 'OS', 'Đen', 'PK67-OS', NULL, 10),
(68, 'OS', 'Nâu', 'PK68-OS', NULL, 8),
(69, 'OS', 'Be', 'PK69-OS', NULL, 8),
(70, 'OS', 'Đen', 'PK70-OS', NULL, 8),
(71, 'OS', 'Be', 'PK71-OS', NULL, 8),
(72, 'OS', 'Vàng kim', 'PK72-OS', NULL, 8),
(73, 'OS', 'Đen', 'PK73-OS', NULL, 8),
(74, 'OS', 'Nâu', 'PK74-OS', NULL, 8),
(75, 'OS', 'Nâu', 'PK75-OS', NULL, 8),
(76, 'OS', 'Bạc', 'PK76-OS', NULL, 8),
(77, 'OS', 'Bạc', 'PK77-OS', NULL, 8),
(78, 'OS', 'Bạc', 'PK78-OS', NULL, 8),
(79, 'OS', 'Bạc', 'PK79-OS', NULL, 8),
(80, 'OS', 'Bạc', 'PK80-OS', NULL, 8),
(81, 'OS', 'Bạc', 'PK81-OS', NULL, 8),
(82, 'OS', 'Bạc', 'PK82-OS', NULL, 8),
(83, 'OS', 'Bạc', 'PK83-OS', NULL, 8),
(84, 'OS', 'Bạc', 'PK84-OS', NULL, 8),
(85, 'OS', 'Hồng', 'PK85-OS', NULL, 10),
(86, 'OS', 'Be', 'PK86-OS', NULL, 10),
(87, 'OS', 'Kem', 'PK87-OS', NULL, 10),
(88, 'OS', 'Đỏ', 'PK88-OS', NULL, 10),
(89, 'OS', 'Hồng', 'PK89-OS', NULL, 10),
(90, 'OS', 'Nâu', 'PK90-OS', NULL, 10),
(91, 'OS', 'Đen', 'PK91-OS', NULL, 10),
(92, 'OS', 'Nâu', 'PK92-OS', NULL, 10),
(93, 'OS', 'Nâu', 'PK93-OS', NULL, 10),
(94, 'OS', 'Đen', 'PK94-OS', NULL, 10),
-- Giày 95-116 (sizes 36-39)
(95, '36', 'Be', 'G95-36-BE', NULL, 2),
(95, '37', 'Be', 'G95-37-BE', NULL, 2),
(95, '38', 'Be', 'G95-38-BE', NULL, 2),
(95, '39', 'Be', 'G95-39-BE', NULL, 2),
(96, '36', 'Be', 'G96-36-BE', NULL, 2),
(96, '37', 'Be', 'G96-37-BE', NULL, 2),
(96, '38', 'Be', 'G96-38-BE', NULL, 2),
(96, '39', 'Be', 'G96-39-BE', NULL, 2),
(97, '36', 'Đen', 'G97-36-DEN', NULL, 2),
(97, '37', 'Đen', 'G97-37-DEN', NULL, 2),
(97, '38', 'Đen', 'G97-38-DEN', NULL, 2),
(97, '39', 'Đen', 'G97-39-DEN', NULL, 2),
(98, '36', 'Trắng', 'G98-36-TRANG', NULL, 2),
(98, '37', 'Trắng', 'G98-37-TRANG', NULL, 2),
(98, '38', 'Trắng', 'G98-38-TRANG', NULL, 2),
(98, '39', 'Trắng', 'G98-39-TRANG', NULL, 2),
(99, '36', 'Trắng', 'G99-36-TRANG', NULL, 2),
(99, '37', 'Trắng', 'G99-37-TRANG', NULL, 2),
(99, '38', 'Trắng', 'G99-38-TRANG', NULL, 2),
(99, '39', 'Trắng', 'G99-39-TRANG', NULL, 2),
(100, '36', 'Be', 'G100-36-BE', NULL, 2),
(100, '37', 'Be', 'G100-37-BE', NULL, 2),
(100, '38', 'Be', 'G100-38-BE', NULL, 2),
(100, '39', 'Be', 'G100-39-BE', NULL, 2),
(101, '36', 'Hồng', 'G101-36-HONG', NULL, 2),
(101, '37', 'Hồng', 'G101-37-HONG', NULL, 2),
(101, '38', 'Hồng', 'G101-38-HONG', NULL, 2),
(101, '39', 'Hồng', 'G101-39-HONG', NULL, 2),
(102, '36', 'Be', 'G102-36-BE', NULL, 2),
(102, '37', 'Be', 'G102-37-BE', NULL, 2),
(102, '38', 'Be', 'G102-38-BE', NULL, 2),
(102, '39', 'Be', 'G102-39-BE', NULL, 2),
(103, '36', 'Đen', 'G103-36-DEN', NULL, 2),
(103, '37', 'Đen', 'G103-37-DEN', NULL, 2),
(103, '38', 'Đen', 'G103-38-DEN', NULL, 2),
(103, '39', 'Đen', 'G103-39-DEN', NULL, 2),
(104, '36', 'Be', 'G104-36-BE', NULL, 2),
(104, '37', 'Be', 'G104-37-BE', NULL, 2),
(104, '38', 'Be', 'G104-38-BE', NULL, 2),
(104, '39', 'Be', 'G104-39-BE', NULL, 2),
(105, '36', 'Đen', 'G105-36-DEN', NULL, 2),
(105, '37', 'Đen', 'G105-37-DEN', NULL, 2),
(105, '38', 'Đen', 'G105-38-DEN', NULL, 2),
(105, '39', 'Đen', 'G105-39-DEN', NULL, 2),
(106, '36', 'Hồng', 'G106-36-HONG', NULL, 2),
(106, '37', 'Hồng', 'G106-37-HONG', NULL, 2),
(106, '38', 'Hồng', 'G106-38-HONG', NULL, 2),
(106, '39', 'Hồng', 'G106-39-HONG', NULL, 2),
(107, '36', 'Be', 'G107-36-BE', NULL, 2),
(107, '37', 'Be', 'G107-37-BE', NULL, 2),
(107, '38', 'Be', 'G107-38-BE', NULL, 2),
(107, '39', 'Be', 'G107-39-BE', NULL, 2),
(108, '36', 'Đen', 'G108-36-DEN', NULL, 2),
(108, '37', 'Đen', 'G108-37-DEN', NULL, 2),
(108, '38', 'Đen', 'G108-38-DEN', NULL, 2),
(108, '39', 'Đen', 'G108-39-DEN', NULL, 2),
(109, '36', 'Be', 'G109-36-BE', NULL, 2),
(109, '37', 'Be', 'G109-37-BE', NULL, 2),
(109, '38', 'Be', 'G109-38-BE', NULL, 2),
(109, '39', 'Be', 'G109-39-BE', NULL, 2),
(110, '36', 'Đen', 'G110-36-DEN', NULL, 2),
(110, '37', 'Đen', 'G110-37-DEN', NULL, 2),
(110, '38', 'Đen', 'G110-38-DEN', NULL, 2),
(110, '39', 'Đen', 'G110-39-DEN', NULL, 2),
(111, '36', 'Be', 'G111-36-BE', NULL, 2),
(111, '37', 'Be', 'G111-37-BE', NULL, 2),
(111, '38', 'Be', 'G111-38-BE', NULL, 2),
(111, '39', 'Be', 'G111-39-BE', NULL, 2),
(112, '36', 'Đen', 'G112-36-DEN', NULL, 2),
(112, '37', 'Đen', 'G112-37-DEN', NULL, 2),
(112, '38', 'Đen', 'G112-38-DEN', NULL, 2),
(112, '39', 'Đen', 'G112-39-DEN', NULL, 2),
(113, '36', 'Hồng', 'G113-36-HONG', NULL, 2),
(113, '37', 'Hồng', 'G113-37-HONG', NULL, 2),
(113, '38', 'Hồng', 'G113-38-HONG', NULL, 2),
(113, '39', 'Hồng', 'G113-39-HONG', NULL, 2),
(114, '36', 'Be', 'G114-36-BE', NULL, 2),
(114, '37', 'Be', 'G114-37-BE', NULL, 2),
(114, '38', 'Be', 'G114-38-BE', NULL, 2),
(114, '39', 'Be', 'G114-39-BE', NULL, 2),
(115, '36', 'Đen', 'G115-36-DEN', NULL, 2),
(115, '37', 'Đen', 'G115-37-DEN', NULL, 2),
(115, '38', 'Đen', 'G115-38-DEN', NULL, 2),
(115, '39', 'Đen', 'G115-39-DEN', NULL, 2),
(116, '36', 'Be', 'G116-36-BE', NULL, 2),
(116, '37', 'Be', 'G116-37-BE', NULL, 2),
(116, '38', 'Be', 'G116-38-BE', NULL, 2),
(116, '39', 'Be', 'G116-39-BE', NULL, 2),
-- Váy Đi Biển 117-131
(117, 'S', 'Trắng', 'VDB117-S-TRANG', NULL, 2),
(117, 'M', 'Hoa', 'VDB117-M-HOA', NULL, 3),
(117, 'L', 'Be', 'VDB117-L-BE', NULL, 2),
(118, 'S', 'Trắng', 'VDB118-S-TRANG', NULL, 2),
(118, 'M', 'Be', 'VDB118-M-BE', NULL, 3),
(118, 'L', 'Đen', 'VDB118-L-DEN', NULL, 2),
(119, 'S', 'Trắng', 'VDB119-S-TRANG', NULL, 2),
(119, 'M', 'Be', 'VDB119-M-BE', NULL, 3),
(119, 'L', 'Đen', 'VDB119-L-DEN', NULL, 2),
(120, 'S', 'Trắng', 'VDB120-S-TRANG', NULL, 2),
(120, 'M', 'Hoa', 'VDB120-M-HOA', NULL, 3),
(120, 'L', 'Be', 'VDB120-L-BE', NULL, 2),
(121, 'S', 'Trắng', 'VDB121-S-TRANG', NULL, 2),
(121, 'M', 'Hoa', 'VDB121-M-HOA', NULL, 3),
(121, 'L', 'Be', 'VDB121-L-BE', NULL, 2),
(122, 'S', 'Trắng', 'VDB122-S-TRANG', NULL, 2),
(122, 'M', 'Be', 'VDB122-M-BE', NULL, 3),
(122, 'L', 'Đen', 'VDB122-L-DEN', NULL, 2),
(123, 'S', 'Trắng', 'VDB123-S-TRANG', NULL, 2),
(123, 'M', 'Hoa', 'VDB123-M-HOA', NULL, 3),
(123, 'L', 'Be', 'VDB123-L-BE', NULL, 2),
(124, 'S', 'Trắng', 'VDB124-S-TRANG', NULL, 2),
(124, 'M', 'Hoa', 'VDB124-M-HOA', NULL, 3),
(124, 'L', 'Be', 'VDB124-L-BE', NULL, 2),
(125, 'S', 'Trắng', 'VDB125-S-TRANG', NULL, 2),
(125, 'M', 'Be', 'VDB125-M-BE', NULL, 3),
(125, 'L', 'Đen', 'VDB125-L-DEN', NULL, 2),
(126, 'S', 'Trắng', 'VDB126-S-TRANG', NULL, 2),
(126, 'M', 'Hoa', 'VDB126-M-HOA', NULL, 3),
(126, 'L', 'Be', 'VDB126-L-BE', NULL, 2),
(127, 'S', 'Trắng', 'VDB127-S-TRANG', NULL, 2),
(127, 'M', 'Hoa', 'VDB127-M-HOA', NULL, 3),
(127, 'L', 'Be', 'VDB127-L-BE', NULL, 2),
(128, 'S', 'Trắng', 'VDB128-S-TRANG', NULL, 2),
(128, 'M', 'Be', 'VDB128-M-BE', NULL, 3),
(128, 'L', 'Đen', 'VDB128-L-DEN', NULL, 2),
(129, 'S', 'Trắng', 'VDB129-S-TRANG', NULL, 2),
(129, 'M', 'Hoa', 'VDB129-M-HOA', NULL, 3),
(129, 'L', 'Be', 'VDB129-L-BE', NULL, 2),
(130, 'S', 'Trắng', 'VDB130-S-TRANG', NULL, 2),
(130, 'M', 'Hoa', 'VDB130-M-HOA', NULL, 3),
(130, 'L', 'Be', 'VDB130-L-BE', NULL, 2),
(131, 'S', 'Trắng', 'VDB131-S-TRANG', NULL, 2),
(131, 'M', 'Be', 'VDB131-M-BE', NULL, 3),
(131, 'L', 'Đen', 'VDB131-L-DEN', NULL, 2);